project:
  type: website
  output-dir: docs
  render:
    - /index.qmd
  post-render:
    - scripts/post-render.py

website:
  title: "Quarto + Shinylive"
  navbar:
    search: true
    right:
      - icon: github
        href: https://shiny.rstudio.com/py/

format:
  html:
    toc: true
