project:
  type: website
  output-dir: docs
  render:
    - /index.qmd
  resources:
    # Need to tell it to copy over the Shinylive serviceworker. Hopefully in the
    # future this won't be needed.
    - /shinylive-sw.js

website:
  title: "Quarto + Shinylive"
  navbar:
    search: true
    right:
      - icon: github
        href: https://shiny.rstudio.com/py/

format:
  html:
    toc: true

filters:
  - shinylive
